[package]
name = "probables"
version = "0.1.0"
edition = "2018"
authors = ["Ali <alideveloper95@gmail.com>"]
description = "Rust data structure"
readme = "README.md"
license = "MIT"
keywords = ["data-structure", "tools"]
categories = ["command-line-utilities", "development-tools::cargo-plugins","algorithms"]
license-file = "LICENSE"
repositry = "https://github.com/WisdomDwarfs/probable-potato"
documentation = "https://docs.rs/probables"
publish = true




# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
